---
title: "Assignment 1"
author: "Chien-Che Hung"
date: "2020-09-21"
pagetitle: "Assignment 1"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(ggplot2) 
library(tidyverse)
library(forcats)
library(plyr)
ttc_delay <- read_xlsx("/Users/frankhung/Documents/FHDocument/2020_2021/STA304/Assignments/Assignment\ 1/ttc-streetcar-delay-data-2019.xlsx")
```

# Introduction

```{r}

ggplot(ttc_delay, aes(x = forcats::fct_infreq(Day))) +
  geom_bar(stat = "count") +
  theme_minimal()


ggplot(ttc_delay, aes(x = forcats::fct_infreq(Incident))) +
  geom_bar(stat = "count") +
  theme_minimal()

aggregate(ttc_delay$`Min Delay`, by = list(ttc_delay$Incident), mean)

delay_sum <- as.data.frame(aggregate(`Min Delay` ~ Incident, ttc_delay, mean))


delay_sum$Incident <- factor(delay_sum$Incident, levels = delay_sum$Incident[order(delay_sum$`Min Delay`, decreasing = TRUE)])

delay_sum %>%
  ggplot(aes(x = Incident, y = `Min Delay`)) +
  geom_bar(stat = "identity") + 
  labs(title = "Average Delay Time According to Incidents") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.6, hjust=0.5))

```

